apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: OnlineTable
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/onlinetable
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    name: main.default.online_table
    spec:
    - primaryKeyColumns:
      - id
      runTriggered:
      - {}
      sourceTableFullName: main.default.source_table
