apiVersion: security.databricks.crossplane.io/v1alpha1
kind: AccessControlRuleSet
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/accesscontrolruleset
  labels:
    testing.upbound.io/example-name: automation_sp_rule_set
  name: automation-sp-rule-set
spec:
  forProvider:
    grantRules:
    - principals:
      - ${data.databricks_group.ds.acl_principal_id}
      role: roles/servicePrincipal.user
    name: accounts/${local.account_id}/servicePrincipals/${databricks_service_principal.automation_sp.application_id}/ruleSets/default

---

apiVersion: security.databricks.crossplane.io/v1alpha1
kind: ServicePrincipal
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/accesscontrolruleset
  labels:
    testing.upbound.io/example-name: automation_sp
  name: automation-sp
spec:
  forProvider:
    displayName: SP_FOR_AUTOMATION
