apiVersion: security.databricks.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: publishing_api
  name: publishing-api
spec:
  forProvider:
    key: publishing_api
    scope: ${databricks_secret_scope.app.id}
    stringValueSecretRef:
      key: attribute.example.value
      name: example-
      namespace: upbound-system

---

apiVersion: compute.databricks.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    sparkConf:
      fs.azure.account.oauth2.client.secret: ${databricks_secret.publishing_api.config_reference}

---

apiVersion: security.databricks.crossplane.io/v1alpha1
kind: SecretScope
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    name: application-secret-scope
