apiVersion: security.databricks.crossplane.io/v1alpha1
kind: SecretACL
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secretacl
  labels:
    testing.upbound.io/example-name: my_secret_acl
  name: my-secret-acl
spec:
  forProvider:
    permission: READ
    principal: ${databricks_group.ds.display_name}
    scope: terraform-demo-scope

---

apiVersion: security.databricks.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secretacl
  labels:
    testing.upbound.io/example-name: ds
  name: ds
spec:
  forProvider:
    displayName: data-scientists

---

apiVersion: security.databricks.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secretacl
  labels:
    testing.upbound.io/example-name: publishing_api
  name: publishing-api
spec:
  forProvider:
    key: publishing_api
    scope: app-secret-scope
    stringValueSecretRef:
      key: attribute.example.value
      name: example-
      namespace: upbound-system

---

apiVersion: security.databricks.crossplane.io/v1alpha1
kind: SecretScope
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secretacl
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    name: app-secret-scope
