// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AwsKeyInfoInitParameters struct {

	// The AWS KMS key alias.
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// The AWS KMS key's Amazon Resource Name (ARN).
	KeyArn *string `json:"keyArn,omitempty" tf:"key_arn,omitempty"`

	// (Computed) The AWS region in which KMS key is deployed to. This is not required.
	KeyRegion *string `json:"keyRegion,omitempty" tf:"key_region,omitempty"`
}

type AwsKeyInfoObservation struct {

	// The AWS KMS key alias.
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// The AWS KMS key's Amazon Resource Name (ARN).
	KeyArn *string `json:"keyArn,omitempty" tf:"key_arn,omitempty"`

	// (Computed) The AWS region in which KMS key is deployed to. This is not required.
	KeyRegion *string `json:"keyRegion,omitempty" tf:"key_region,omitempty"`
}

type AwsKeyInfoParameters struct {

	// The AWS KMS key alias.
	// +kubebuilder:validation:Optional
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// The AWS KMS key's Amazon Resource Name (ARN).
	// +kubebuilder:validation:Optional
	KeyArn *string `json:"keyArn" tf:"key_arn,omitempty"`

	// (Computed) The AWS region in which KMS key is deployed to. This is not required.
	// +kubebuilder:validation:Optional
	KeyRegion *string `json:"keyRegion,omitempty" tf:"key_region,omitempty"`
}

type GCPKeyInfoInitParameters struct {

	// The GCP KMS key's resource name.
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`
}

type GCPKeyInfoObservation struct {

	// The GCP KMS key's resource name.
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`
}

type GCPKeyInfoParameters struct {

	// The GCP KMS key's resource name.
	// +kubebuilder:validation:Optional
	KMSKeyID *string `json:"kmsKeyId" tf:"kms_key_id,omitempty"`
}

type MwsCustomerManagedKeysInitParameters struct {

	// Account Id that could be found in the top right corner of Accounts Console
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// This field is a block and is documented below. This conflicts with gcp_key_info
	AwsKeyInfo []AwsKeyInfoInitParameters `json:"awsKeyInfo,omitempty" tf:"aws_key_info,omitempty"`

	// (Integer) Time in epoch milliseconds when the customer key was created.
	CreationTime *float64 `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// (String) ID of the encryption key configuration object.
	CustomerManagedKeyID *string `json:"customerManagedKeyId,omitempty" tf:"customer_managed_key_id,omitempty"`

	// This field is a block and is documented below. This conflicts with aws_key_info
	GCPKeyInfo []GCPKeyInfoInitParameters `json:"gcpKeyInfo,omitempty" tf:"gcp_key_info,omitempty"`

	// (since v0.3.4) List of use cases for which this key will be used. If you've used the resource before, please add  Possible values are:
	UseCases []*string `json:"useCases,omitempty" tf:"use_cases,omitempty"`
}

type MwsCustomerManagedKeysObservation struct {

	// Account Id that could be found in the top right corner of Accounts Console
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// This field is a block and is documented below. This conflicts with gcp_key_info
	AwsKeyInfo []AwsKeyInfoObservation `json:"awsKeyInfo,omitempty" tf:"aws_key_info,omitempty"`

	// (Integer) Time in epoch milliseconds when the customer key was created.
	CreationTime *float64 `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// (String) ID of the encryption key configuration object.
	CustomerManagedKeyID *string `json:"customerManagedKeyId,omitempty" tf:"customer_managed_key_id,omitempty"`

	// This field is a block and is documented below. This conflicts with aws_key_info
	GCPKeyInfo []GCPKeyInfoObservation `json:"gcpKeyInfo,omitempty" tf:"gcp_key_info,omitempty"`

	// Canonical unique identifier for the mws customer managed keys.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (since v0.3.4) List of use cases for which this key will be used. If you've used the resource before, please add  Possible values are:
	UseCases []*string `json:"useCases,omitempty" tf:"use_cases,omitempty"`
}

type MwsCustomerManagedKeysParameters struct {

	// Account Id that could be found in the top right corner of Accounts Console
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// This field is a block and is documented below. This conflicts with gcp_key_info
	// +kubebuilder:validation:Optional
	AwsKeyInfo []AwsKeyInfoParameters `json:"awsKeyInfo,omitempty" tf:"aws_key_info,omitempty"`

	// (Integer) Time in epoch milliseconds when the customer key was created.
	// +kubebuilder:validation:Optional
	CreationTime *float64 `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// (String) ID of the encryption key configuration object.
	// +kubebuilder:validation:Optional
	CustomerManagedKeyID *string `json:"customerManagedKeyId,omitempty" tf:"customer_managed_key_id,omitempty"`

	// This field is a block and is documented below. This conflicts with aws_key_info
	// +kubebuilder:validation:Optional
	GCPKeyInfo []GCPKeyInfoParameters `json:"gcpKeyInfo,omitempty" tf:"gcp_key_info,omitempty"`

	// (since v0.3.4) List of use cases for which this key will be used. If you've used the resource before, please add  Possible values are:
	// +kubebuilder:validation:Optional
	UseCases []*string `json:"useCases,omitempty" tf:"use_cases,omitempty"`
}

// MwsCustomerManagedKeysSpec defines the desired state of MwsCustomerManagedKeys
type MwsCustomerManagedKeysSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MwsCustomerManagedKeysParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MwsCustomerManagedKeysInitParameters `json:"initProvider,omitempty"`
}

// MwsCustomerManagedKeysStatus defines the observed state of MwsCustomerManagedKeys.
type MwsCustomerManagedKeysStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MwsCustomerManagedKeysObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MwsCustomerManagedKeys is the Schema for the MwsCustomerManagedKeyss API. ""subcategory: "Deployment"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,}
type MwsCustomerManagedKeys struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.useCases) || (has(self.initProvider) && has(self.initProvider.useCases))",message="spec.forProvider.useCases is a required parameter"
	Spec   MwsCustomerManagedKeysSpec   `json:"spec"`
	Status MwsCustomerManagedKeysStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MwsCustomerManagedKeysList contains a list of MwsCustomerManagedKeyss
type MwsCustomerManagedKeysList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MwsCustomerManagedKeys `json:"items"`
}

// Repository type metadata.
var (
	MwsCustomerManagedKeys_Kind             = "MwsCustomerManagedKeys"
	MwsCustomerManagedKeys_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MwsCustomerManagedKeys_Kind}.String()
	MwsCustomerManagedKeys_KindAPIVersion   = MwsCustomerManagedKeys_Kind + "." + CRDGroupVersion.String()
	MwsCustomerManagedKeys_GroupVersionKind = CRDGroupVersion.WithKind(MwsCustomerManagedKeys_Kind)
)

func init() {
	SchemeBuilder.Register(&MwsCustomerManagedKeys{}, &MwsCustomerManagedKeysList{})
}
