// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AwsStableIPRuleInitParameters struct {

	// list of IP CIDR blocks.
	CidrBlocks []*string `json:"cidrBlocks,omitempty" tf:"cidr_blocks,omitempty"`
}

type AwsStableIPRuleObservation struct {

	// list of IP CIDR blocks.
	CidrBlocks []*string `json:"cidrBlocks,omitempty" tf:"cidr_blocks,omitempty"`
}

type AwsStableIPRuleParameters struct {

	// list of IP CIDR blocks.
	// +kubebuilder:validation:Optional
	CidrBlocks []*string `json:"cidrBlocks,omitempty" tf:"cidr_blocks,omitempty"`
}

type AzurePrivateEndpointRulesInitParameters struct {
	ConnectionState *string `json:"connectionState,omitempty" tf:"connection_state,omitempty"`

	CreationTime *float64 `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	Deactivated *bool `json:"deactivated,omitempty" tf:"deactivated,omitempty"`

	DeactivatedAt *float64 `json:"deactivatedAt,omitempty" tf:"deactivated_at,omitempty"`

	// Name of Network Connectivity Config in Databricks Account. Change forces creation of a new resource.
	EndpointName *string `json:"endpointName,omitempty" tf:"endpoint_name,omitempty"`

	// combination of account_id and network_connectivity_config_id separated by / character
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Canonical unique identifier of Network Connectivity Config in Databricks Account
	NetworkConnectivityConfigID *string `json:"networkConnectivityConfigId,omitempty" tf:"network_connectivity_config_id,omitempty"`

	// combination of account_id and network_connectivity_config_id separated by / character
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// combination of account_id and network_connectivity_config_id separated by / character
	RuleID *string `json:"ruleId,omitempty" tf:"rule_id,omitempty"`

	UpdatedTime *float64 `json:"updatedTime,omitempty" tf:"updated_time,omitempty"`
}

type AzurePrivateEndpointRulesObservation struct {
	ConnectionState *string `json:"connectionState,omitempty" tf:"connection_state,omitempty"`

	CreationTime *float64 `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	Deactivated *bool `json:"deactivated,omitempty" tf:"deactivated,omitempty"`

	DeactivatedAt *float64 `json:"deactivatedAt,omitempty" tf:"deactivated_at,omitempty"`

	// Name of Network Connectivity Config in Databricks Account. Change forces creation of a new resource.
	EndpointName *string `json:"endpointName,omitempty" tf:"endpoint_name,omitempty"`

	// combination of account_id and network_connectivity_config_id separated by / character
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Canonical unique identifier of Network Connectivity Config in Databricks Account
	NetworkConnectivityConfigID *string `json:"networkConnectivityConfigId,omitempty" tf:"network_connectivity_config_id,omitempty"`

	// combination of account_id and network_connectivity_config_id separated by / character
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// combination of account_id and network_connectivity_config_id separated by / character
	RuleID *string `json:"ruleId,omitempty" tf:"rule_id,omitempty"`

	UpdatedTime *float64 `json:"updatedTime,omitempty" tf:"updated_time,omitempty"`
}

type AzurePrivateEndpointRulesParameters struct {

	// +kubebuilder:validation:Optional
	ConnectionState *string `json:"connectionState,omitempty" tf:"connection_state,omitempty"`

	// +kubebuilder:validation:Optional
	CreationTime *float64 `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// +kubebuilder:validation:Optional
	Deactivated *bool `json:"deactivated,omitempty" tf:"deactivated,omitempty"`

	// +kubebuilder:validation:Optional
	DeactivatedAt *float64 `json:"deactivatedAt,omitempty" tf:"deactivated_at,omitempty"`

	// Name of Network Connectivity Config in Databricks Account. Change forces creation of a new resource.
	// +kubebuilder:validation:Optional
	EndpointName *string `json:"endpointName,omitempty" tf:"endpoint_name,omitempty"`

	// combination of account_id and network_connectivity_config_id separated by / character
	// +kubebuilder:validation:Optional
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Canonical unique identifier of Network Connectivity Config in Databricks Account
	// +kubebuilder:validation:Optional
	NetworkConnectivityConfigID *string `json:"networkConnectivityConfigId,omitempty" tf:"network_connectivity_config_id,omitempty"`

	// combination of account_id and network_connectivity_config_id separated by / character
	// +kubebuilder:validation:Optional
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// combination of account_id and network_connectivity_config_id separated by / character
	// +kubebuilder:validation:Optional
	RuleID *string `json:"ruleId,omitempty" tf:"rule_id,omitempty"`

	// +kubebuilder:validation:Optional
	UpdatedTime *float64 `json:"updatedTime,omitempty" tf:"updated_time,omitempty"`
}

type AzureServiceEndpointRuleInitParameters struct {

	// list of subnets from which Databricks network traffic originates when accessing your Azure resources.
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`

	// the Azure region in which this service endpoint rule applies.
	TargetRegion *string `json:"targetRegion,omitempty" tf:"target_region,omitempty"`

	// the Azure services to which this service endpoint rule applies to.
	TargetServices []*string `json:"targetServices,omitempty" tf:"target_services,omitempty"`
}

type AzureServiceEndpointRuleObservation struct {

	// list of subnets from which Databricks network traffic originates when accessing your Azure resources.
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`

	// the Azure region in which this service endpoint rule applies.
	TargetRegion *string `json:"targetRegion,omitempty" tf:"target_region,omitempty"`

	// the Azure services to which this service endpoint rule applies to.
	TargetServices []*string `json:"targetServices,omitempty" tf:"target_services,omitempty"`
}

type AzureServiceEndpointRuleParameters struct {

	// list of subnets from which Databricks network traffic originates when accessing your Azure resources.
	// +kubebuilder:validation:Optional
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`

	// the Azure region in which this service endpoint rule applies.
	// +kubebuilder:validation:Optional
	TargetRegion *string `json:"targetRegion,omitempty" tf:"target_region,omitempty"`

	// the Azure services to which this service endpoint rule applies to.
	// +kubebuilder:validation:Optional
	TargetServices []*string `json:"targetServices,omitempty" tf:"target_services,omitempty"`
}

type DefaultRulesInitParameters struct {

	// block with information about stable AWS IP CIDR blocks. You can use these to configure the firewall of your resources to allow traffic from your Databricks workspace.  Consists of the following fields:
	AwsStableIPRule []AwsStableIPRuleInitParameters `json:"awsStableIpRule,omitempty" tf:"aws_stable_ip_rule,omitempty"`

	// block with information about stable Azure service endpoints. You can configure the firewall of your Azure resources to allow traffic from your Databricks serverless compute resources.  Consists of the following fields:
	AzureServiceEndpointRule []AzureServiceEndpointRuleInitParameters `json:"azureServiceEndpointRule,omitempty" tf:"azure_service_endpoint_rule,omitempty"`
}

type DefaultRulesObservation struct {

	// block with information about stable AWS IP CIDR blocks. You can use these to configure the firewall of your resources to allow traffic from your Databricks workspace.  Consists of the following fields:
	AwsStableIPRule []AwsStableIPRuleObservation `json:"awsStableIpRule,omitempty" tf:"aws_stable_ip_rule,omitempty"`

	// block with information about stable Azure service endpoints. You can configure the firewall of your Azure resources to allow traffic from your Databricks serverless compute resources.  Consists of the following fields:
	AzureServiceEndpointRule []AzureServiceEndpointRuleObservation `json:"azureServiceEndpointRule,omitempty" tf:"azure_service_endpoint_rule,omitempty"`
}

type DefaultRulesParameters struct {

	// block with information about stable AWS IP CIDR blocks. You can use these to configure the firewall of your resources to allow traffic from your Databricks workspace.  Consists of the following fields:
	// +kubebuilder:validation:Optional
	AwsStableIPRule []AwsStableIPRuleParameters `json:"awsStableIpRule,omitempty" tf:"aws_stable_ip_rule,omitempty"`

	// block with information about stable Azure service endpoints. You can configure the firewall of your Azure resources to allow traffic from your Databricks serverless compute resources.  Consists of the following fields:
	// +kubebuilder:validation:Optional
	AzureServiceEndpointRule []AzureServiceEndpointRuleParameters `json:"azureServiceEndpointRule,omitempty" tf:"azure_service_endpoint_rule,omitempty"`
}

type EgressConfigInitParameters struct {

	// block describing network connectivity rules that are applied by default without resource specific configurations.  Consists of the following fields:
	DefaultRules []DefaultRulesInitParameters `json:"defaultRules,omitempty" tf:"default_rules,omitempty"`

	// block describing network connectivity rules that configured for each destinations. These rules override default rules.  Consists of the following fields:
	TargetRules []TargetRulesInitParameters `json:"targetRules,omitempty" tf:"target_rules,omitempty"`
}

type EgressConfigObservation struct {

	// block describing network connectivity rules that are applied by default without resource specific configurations.  Consists of the following fields:
	DefaultRules []DefaultRulesObservation `json:"defaultRules,omitempty" tf:"default_rules,omitempty"`

	// block describing network connectivity rules that configured for each destinations. These rules override default rules.  Consists of the following fields:
	TargetRules []TargetRulesObservation `json:"targetRules,omitempty" tf:"target_rules,omitempty"`
}

type EgressConfigParameters struct {

	// block describing network connectivity rules that are applied by default without resource specific configurations.  Consists of the following fields:
	// +kubebuilder:validation:Optional
	DefaultRules []DefaultRulesParameters `json:"defaultRules,omitempty" tf:"default_rules,omitempty"`

	// block describing network connectivity rules that configured for each destinations. These rules override default rules.  Consists of the following fields:
	// +kubebuilder:validation:Optional
	TargetRules []TargetRulesParameters `json:"targetRules,omitempty" tf:"target_rules,omitempty"`
}

type MwsNetworkConnectivityConfigInitParameters struct {

	// combination of account_id and network_connectivity_config_id separated by / character
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	CreationTime *float64 `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	EgressConfig []EgressConfigInitParameters `json:"egressConfig,omitempty" tf:"egress_config,omitempty"`

	// Name of Network Connectivity Config in Databricks Account. Change forces creation of a new resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Canonical unique identifier of Network Connectivity Config in Databricks Account
	NetworkConnectivityConfigID *string `json:"networkConnectivityConfigId,omitempty" tf:"network_connectivity_config_id,omitempty"`

	// Region of the Network Connectivity Config. NCCs can only be referenced by your workspaces in the same region. Change forces creation of a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	UpdatedTime *float64 `json:"updatedTime,omitempty" tf:"updated_time,omitempty"`
}

type MwsNetworkConnectivityConfigObservation struct {

	// combination of account_id and network_connectivity_config_id separated by / character
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	CreationTime *float64 `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	EgressConfig []EgressConfigObservation `json:"egressConfig,omitempty" tf:"egress_config,omitempty"`

	// combination of account_id and network_connectivity_config_id separated by / character
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of Network Connectivity Config in Databricks Account. Change forces creation of a new resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Canonical unique identifier of Network Connectivity Config in Databricks Account
	NetworkConnectivityConfigID *string `json:"networkConnectivityConfigId,omitempty" tf:"network_connectivity_config_id,omitempty"`

	// Region of the Network Connectivity Config. NCCs can only be referenced by your workspaces in the same region. Change forces creation of a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	UpdatedTime *float64 `json:"updatedTime,omitempty" tf:"updated_time,omitempty"`
}

type MwsNetworkConnectivityConfigParameters struct {

	// combination of account_id and network_connectivity_config_id separated by / character
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// +kubebuilder:validation:Optional
	CreationTime *float64 `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// +kubebuilder:validation:Optional
	EgressConfig []EgressConfigParameters `json:"egressConfig,omitempty" tf:"egress_config,omitempty"`

	// Name of Network Connectivity Config in Databricks Account. Change forces creation of a new resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Canonical unique identifier of Network Connectivity Config in Databricks Account
	// +kubebuilder:validation:Optional
	NetworkConnectivityConfigID *string `json:"networkConnectivityConfigId,omitempty" tf:"network_connectivity_config_id,omitempty"`

	// Region of the Network Connectivity Config. NCCs can only be referenced by your workspaces in the same region. Change forces creation of a new resource.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// +kubebuilder:validation:Optional
	UpdatedTime *float64 `json:"updatedTime,omitempty" tf:"updated_time,omitempty"`
}

type TargetRulesInitParameters struct {

	// list containing information about configure Azure Private Endpoints.
	AzurePrivateEndpointRules []AzurePrivateEndpointRulesInitParameters `json:"azurePrivateEndpointRules,omitempty" tf:"azure_private_endpoint_rules,omitempty"`
}

type TargetRulesObservation struct {

	// list containing information about configure Azure Private Endpoints.
	AzurePrivateEndpointRules []AzurePrivateEndpointRulesObservation `json:"azurePrivateEndpointRules,omitempty" tf:"azure_private_endpoint_rules,omitempty"`
}

type TargetRulesParameters struct {

	// list containing information about configure Azure Private Endpoints.
	// +kubebuilder:validation:Optional
	AzurePrivateEndpointRules []AzurePrivateEndpointRulesParameters `json:"azurePrivateEndpointRules,omitempty" tf:"azure_private_endpoint_rules,omitempty"`
}

// MwsNetworkConnectivityConfigSpec defines the desired state of MwsNetworkConnectivityConfig
type MwsNetworkConnectivityConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MwsNetworkConnectivityConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MwsNetworkConnectivityConfigInitParameters `json:"initProvider,omitempty"`
}

// MwsNetworkConnectivityConfigStatus defines the observed state of MwsNetworkConnectivityConfig.
type MwsNetworkConnectivityConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MwsNetworkConnectivityConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MwsNetworkConnectivityConfig is the Schema for the MwsNetworkConnectivityConfigs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type MwsNetworkConnectivityConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   MwsNetworkConnectivityConfigSpec   `json:"spec"`
	Status MwsNetworkConnectivityConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MwsNetworkConnectivityConfigList contains a list of MwsNetworkConnectivityConfigs
type MwsNetworkConnectivityConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MwsNetworkConnectivityConfig `json:"items"`
}

// Repository type metadata.
var (
	MwsNetworkConnectivityConfig_Kind             = "MwsNetworkConnectivityConfig"
	MwsNetworkConnectivityConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MwsNetworkConnectivityConfig_Kind}.String()
	MwsNetworkConnectivityConfig_KindAPIVersion   = MwsNetworkConnectivityConfig_Kind + "." + CRDGroupVersion.String()
	MwsNetworkConnectivityConfig_GroupVersionKind = CRDGroupVersion.WithKind(MwsNetworkConnectivityConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&MwsNetworkConnectivityConfig{}, &MwsNetworkConnectivityConfigList{})
}
