//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MwsLogDelivery) DeepCopyInto(out *MwsLogDelivery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MwsLogDelivery.
func (in *MwsLogDelivery) DeepCopy() *MwsLogDelivery {
	if in == nil {
		return nil
	}
	out := new(MwsLogDelivery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MwsLogDelivery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MwsLogDeliveryInitParameters) DeepCopyInto(out *MwsLogDeliveryInitParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.ConfigID != nil {
		in, out := &in.ConfigID, &out.ConfigID
		*out = new(string)
		**out = **in
	}
	if in.ConfigName != nil {
		in, out := &in.ConfigName, &out.ConfigName
		*out = new(string)
		**out = **in
	}
	if in.CredentialsID != nil {
		in, out := &in.CredentialsID, &out.CredentialsID
		*out = new(string)
		**out = **in
	}
	if in.DeliveryPathPrefix != nil {
		in, out := &in.DeliveryPathPrefix, &out.DeliveryPathPrefix
		*out = new(string)
		**out = **in
	}
	if in.DeliveryStartTime != nil {
		in, out := &in.DeliveryStartTime, &out.DeliveryStartTime
		*out = new(string)
		**out = **in
	}
	if in.LogType != nil {
		in, out := &in.LogType, &out.LogType
		*out = new(string)
		**out = **in
	}
	if in.OutputFormat != nil {
		in, out := &in.OutputFormat, &out.OutputFormat
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StorageConfigurationID != nil {
		in, out := &in.StorageConfigurationID, &out.StorageConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.WorkspaceIdsFilter != nil {
		in, out := &in.WorkspaceIdsFilter, &out.WorkspaceIdsFilter
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MwsLogDeliveryInitParameters.
func (in *MwsLogDeliveryInitParameters) DeepCopy() *MwsLogDeliveryInitParameters {
	if in == nil {
		return nil
	}
	out := new(MwsLogDeliveryInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MwsLogDeliveryList) DeepCopyInto(out *MwsLogDeliveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MwsLogDelivery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MwsLogDeliveryList.
func (in *MwsLogDeliveryList) DeepCopy() *MwsLogDeliveryList {
	if in == nil {
		return nil
	}
	out := new(MwsLogDeliveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MwsLogDeliveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MwsLogDeliveryObservation) DeepCopyInto(out *MwsLogDeliveryObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.ConfigID != nil {
		in, out := &in.ConfigID, &out.ConfigID
		*out = new(string)
		**out = **in
	}
	if in.ConfigName != nil {
		in, out := &in.ConfigName, &out.ConfigName
		*out = new(string)
		**out = **in
	}
	if in.CredentialsID != nil {
		in, out := &in.CredentialsID, &out.CredentialsID
		*out = new(string)
		**out = **in
	}
	if in.DeliveryPathPrefix != nil {
		in, out := &in.DeliveryPathPrefix, &out.DeliveryPathPrefix
		*out = new(string)
		**out = **in
	}
	if in.DeliveryStartTime != nil {
		in, out := &in.DeliveryStartTime, &out.DeliveryStartTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LogType != nil {
		in, out := &in.LogType, &out.LogType
		*out = new(string)
		**out = **in
	}
	if in.OutputFormat != nil {
		in, out := &in.OutputFormat, &out.OutputFormat
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StorageConfigurationID != nil {
		in, out := &in.StorageConfigurationID, &out.StorageConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.WorkspaceIdsFilter != nil {
		in, out := &in.WorkspaceIdsFilter, &out.WorkspaceIdsFilter
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MwsLogDeliveryObservation.
func (in *MwsLogDeliveryObservation) DeepCopy() *MwsLogDeliveryObservation {
	if in == nil {
		return nil
	}
	out := new(MwsLogDeliveryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MwsLogDeliveryParameters) DeepCopyInto(out *MwsLogDeliveryParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.ConfigID != nil {
		in, out := &in.ConfigID, &out.ConfigID
		*out = new(string)
		**out = **in
	}
	if in.ConfigName != nil {
		in, out := &in.ConfigName, &out.ConfigName
		*out = new(string)
		**out = **in
	}
	if in.CredentialsID != nil {
		in, out := &in.CredentialsID, &out.CredentialsID
		*out = new(string)
		**out = **in
	}
	if in.DeliveryPathPrefix != nil {
		in, out := &in.DeliveryPathPrefix, &out.DeliveryPathPrefix
		*out = new(string)
		**out = **in
	}
	if in.DeliveryStartTime != nil {
		in, out := &in.DeliveryStartTime, &out.DeliveryStartTime
		*out = new(string)
		**out = **in
	}
	if in.LogType != nil {
		in, out := &in.LogType, &out.LogType
		*out = new(string)
		**out = **in
	}
	if in.OutputFormat != nil {
		in, out := &in.OutputFormat, &out.OutputFormat
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StorageConfigurationID != nil {
		in, out := &in.StorageConfigurationID, &out.StorageConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.WorkspaceIdsFilter != nil {
		in, out := &in.WorkspaceIdsFilter, &out.WorkspaceIdsFilter
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MwsLogDeliveryParameters.
func (in *MwsLogDeliveryParameters) DeepCopy() *MwsLogDeliveryParameters {
	if in == nil {
		return nil
	}
	out := new(MwsLogDeliveryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MwsLogDeliverySpec) DeepCopyInto(out *MwsLogDeliverySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MwsLogDeliverySpec.
func (in *MwsLogDeliverySpec) DeepCopy() *MwsLogDeliverySpec {
	if in == nil {
		return nil
	}
	out := new(MwsLogDeliverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MwsLogDeliveryStatus) DeepCopyInto(out *MwsLogDeliveryStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MwsLogDeliveryStatus.
func (in *MwsLogDeliveryStatus) DeepCopy() *MwsLogDeliveryStatus {
	if in == nil {
		return nil
	}
	out := new(MwsLogDeliveryStatus)
	in.DeepCopyInto(out)
	return out
}
