// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ServicePrincipalRoleInitParameters struct {

	// This is the id of the role or instance profile resource.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// This is the id of the service principal resource.
	ServicePrincipalID *string `json:"servicePrincipalId,omitempty" tf:"service_principal_id,omitempty"`
}

type ServicePrincipalRoleObservation struct {

	// The id in the format <service_principal_id>|<role>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// This is the id of the role or instance profile resource.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// This is the id of the service principal resource.
	ServicePrincipalID *string `json:"servicePrincipalId,omitempty" tf:"service_principal_id,omitempty"`
}

type ServicePrincipalRoleParameters struct {

	// This is the id of the role or instance profile resource.
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// This is the id of the service principal resource.
	// +kubebuilder:validation:Optional
	ServicePrincipalID *string `json:"servicePrincipalId,omitempty" tf:"service_principal_id,omitempty"`
}

// ServicePrincipalRoleSpec defines the desired state of ServicePrincipalRole
type ServicePrincipalRoleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServicePrincipalRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServicePrincipalRoleInitParameters `json:"initProvider,omitempty"`
}

// ServicePrincipalRoleStatus defines the observed state of ServicePrincipalRole.
type ServicePrincipalRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServicePrincipalRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServicePrincipalRole is the Schema for the ServicePrincipalRoles API. ""subcategory: "Security"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,}
type ServicePrincipalRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.servicePrincipalId) || (has(self.initProvider) && has(self.initProvider.servicePrincipalId))",message="spec.forProvider.servicePrincipalId is a required parameter"
	Spec   ServicePrincipalRoleSpec   `json:"spec"`
	Status ServicePrincipalRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServicePrincipalRoleList contains a list of ServicePrincipalRoles
type ServicePrincipalRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServicePrincipalRole `json:"items"`
}

// Repository type metadata.
var (
	ServicePrincipalRole_Kind             = "ServicePrincipalRole"
	ServicePrincipalRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServicePrincipalRole_Kind}.String()
	ServicePrincipalRole_KindAPIVersion   = ServicePrincipalRole_Kind + "." + CRDGroupVersion.String()
	ServicePrincipalRole_GroupVersionKind = CRDGroupVersion.WithKind(ServicePrincipalRole_Kind)
)

func init() {
	SchemeBuilder.Register(&ServicePrincipalRole{}, &ServicePrincipalRoleList{})
}
