// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Alert) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Budget) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Catalog) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Cluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Connection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Entitlements) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ExternalLocation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GitCredential) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Grants) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Group) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InstancePool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IPAccessList) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Job) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Library) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MlflowExperiment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MlflowModel) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ModelServing) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Notebook) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PermissionAssignment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Permissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Pipeline) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Provider) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Query) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Schema) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Secret) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretScope) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServicePrincipal) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServicePrincipalRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SQLAlert) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SQLDashboard) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SQLEndpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SQLGlobalConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SQLPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SQLQuery) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SQLTable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SQLVisualization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SQLWidget) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Token) Hub() {}
